---
version: "2.0"

services:
  web:
    image: itzg/minecraft-server
    expose:
      - port: 25565
        proto: tcp
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true                
    env:
      - EULA=TRUE
      - VERSION=1.18.2
      - NETWORK_COMPRESSION_THRESHOLD=512
      - SERVER_NAME=ReeceAkashMinecraft
      - MEMORY=4G
      - TYPE=PAPER
      - OPS=Reecepbcups
      - MAX_PLAYERS=69

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 1.5
        memory:
          size: 5Gi
        storage:
          size: 8Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    akash:
      profile: web
      count: 1