---
version: "2.0"

# chmod 600 ~/.ssh/old/id_rsa
# ssh -p PORT_ASSIGNED -i ~/.ssh/old/id_rsa root@someid.ingress.provider-2.prod.ewr1.akash.pub
services:
  web:
    image: user994455/ubuntu-base:0.2 # Change to arch?
    env:
      - sshport=22000
      - pubkey=<Reeces RSA key ~/.ssh/old/>
    expose:
      - port: 22000
        as: 22000 # SSH port
        to:
          - global: true
      - port: 28865
        as: 28865 # mc server itself
        to:
          - global: true            
      - port: 80
        as: 80 # so we get the URI
        to:
          - global: true          

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 3
        memory:
          size: 6Gi
        storage:
          size: 25Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1