version: "2.0"
services:
  mongo:
    image: mongo:latest
    expose:
      - port: 80 
        to:
          - global: true    
      - port: 27017 
        to:
          - global: true  
    params:
      storage:
        data:
          mount: /data/db
    env:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo17password

profiles:
  compute:
    mongo:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 512Mi
          - name: data
            size: 5Gi
            attributes:
              persistent: true
              class: beta2
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        mongo:
          denom: uakt
          amount: 7500
deployment:
  mongo:
    westcoast:
      profile: mongo
      count: 1