PANEL_DIRECTORY: /root/minecraft-panel
SERVER_DIRECTORY: /root/minecraft-panel/servers
BACKUP_DIRECTORY: /root/minecraft-panel/backups
DOWNLOAD_CACHE: /root/minecraft-panel/downloads
servers:
  proxy:
  - proxy
  spigot:
  - testing
  standalone:
  - ''
firewall:
  allow-ports:
  - 21
  - 22
  - 80
  - 443
  - 25565
  full-access-ip-connections:
  - 127.0.0.1
web-shortner:
  location: /var/www/html/l
  domain: reece.sh/l
Mongo-Authentication:
  myUserAdmin: admin
  myTester: test
