downloadloc: /root/minecraft-panel/downloads
serverloc: /root/minecraft-panel/servers
# Provide a path to the plugin e/g
# if your plugin has a subfolder called sub and the main file was called runner
# sub.runner
# follow this by a dash and the plugins name so your final format is
# sub.runner-Runner
plugins:
 - example-Example
# Don't add all your servers here just change serverloc
# TODO: just show all files in the server dir?
external_servers:
